export const JOBBANK_FILTERS = {
  jobTypes: {
    3: "Fuldtidsjob",
    4: "Studiejob",
    5: "Studieprojekt/speciale",
    6: "Graduate/trainee",
    8: "Vikariat",
    9: "Praktikplads",
    11: "Freelance",
    12: "Ph.d. & Postdoc",
    13: "Deltidsjob",
    14: "Event",
    15: "Iværksætterprojekt",
  },
  educationAreas: {
    20: "Administration", 21: "Økonomi/Revision", 22: "Marketing/Business",
    23: "Jura", 24: "IT", 25: "Sprog/Media/Kommunikation",
    26: "Undervisning/Pædagogik", 28: "Humaniora", 29: "Arkitektur/Kunst/Design",
    30: "Naturvidenskab", 31: "Medicinal/Sundhed", 32: "Fødevarer/Veterinær",
    33: "Teknik/Teknologi", 34: "Samfundsvidenskab", 35: "Produktion/Logistik/Transport",
    37: "Landbrug/Natur", 38: "Human Resources", 41: "Organisation/Ledelse",
    43: "Anlæg/Byggeri/Konstruktion", 44: "Kemi/Biotek/Materialer",
    45: "Klima/Miljø/Energi", 46: "Matematik/Fysik/Nano",
    47: "Elektro/Telekommunikation", 48: "Maskin/Design",
  },
  locations: {
    2: "Storkøbenhavn", 3: "Nordsjælland", 4: "Vestsjælland",
    5: "Sydsjælland & Øer", 6: "Nordjylland", 7: "Midtjylland",
    8: "Østjylland (Aarhus)", 9: "Vestjylland", 10: "Sydøstjylland",
    11: "Sydvestjylland (Esbjerg)", 12: "Sønderjylland", 13: "Fyn",
    14: "Østsjælland", 20: "Bornholm", 21: "Øresundsregionen",
    22: "Grønland & Færøerne", 23: "Udlandet - Sverige",
    24: "Udlandet - Norge", 19: "Udlandet - øvrige",
  },
  workAreas: {
    20: "Administration", 21: "Økonomi/Forvaltning", 22: "Bank/Forsikring",
    23: "Organisation/Forening", 24: "Jura", 25: "Topledelse",
    26: "Ledelse/Planlægning", 27: "Projektledelse", 28: "Human Resources",
    29: "Marketing/Reklame", 30: "Salg", 31: "IT-Software",
    32: "IT-Hardware", 33: "IT-Netværk/Telekomm.", 34: "Internet/Multimedia",
    35: "Kommunikation/Media/SoMe", 36: "Undervisning", 37: "Kunst/Kultur",
    38: "Arkitektur/Design", 39: "Socialvæsen", 40: "Medicinal/Sundhed",
    41: "Forskning/Udvikling", 42: "Teknik", 43: "Data/Analyse",
    44: "Produktion", 45: "Naturvidenskab", 46: "Konstruktion/Beregning",
    47: "Eksport", 48: "Transport/Logistik", 49: "Indkøb",
    50: "Rådgivning/Support", 52: "Politik/Samfund",
  },
  industries: {
    10331: "IT/Tele", 10333: "Medicinal/Biotek/Kemi", 10341: "Kultur/Medier/Underholdning",
    10358: "Finans/Forsikring/Pension", 10359: "Advokat/Revision", 10362: "Stat/Politik/Samfund",
    10363: "Papir/Møbel/Materialer", 10364: "Handel/Service", 10440: "Transport",
    10442: "Forskning/Uddannelse", 11626: "Regioner/Sundhed/Socialvæsen",
    11634: "Elektronik/Maskin", 11669: "Byggeri/Anlæg", 12450: "Vikar/Rekruttering",
    15407: "Fødevarer/Dagligvarer", 15586: "Rådgivning/Konsulentservice",
    16791: "Fagforeninger/A-kasser/Pensionskasser", 16826: "Kommuner",
    17209: "Klima/Energi/Forsyning",
  },
  suitability: { 2: "Nyuddannede", 4: "International baggrund", 5: "Erfarne" },
  remoteWork: { helt: "Helt hjemmearbejde", delvist: "Delvist hjemmearbejde" },
} as const;
