import { readdir } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { validateGuideFrontmatter } from "../web/content/schema.ts";
import { renderGuideHtml } from "../web/render/guide.ts";

const root = process.cwd();
const contentRoot = join(root, "web/content/guides");
const publicRoot = join(root, "web/public");
type Guide = ReturnType<typeof validateGuideFrontmatter> & { route: string; markdownRoute: string; source: string; body: string };

async function markdownFiles(directory: string): Promise<string[]> { const entries = await readdir(directory, { withFileTypes: true }); const nested = await Promise.all(entries.map(async (entry) => entry.isDirectory() ? markdownFiles(join(directory, entry.name)) : entry.isFile() && entry.name === "index.md" ? [join(directory, entry.name)] : [])); return nested.flat(); }
function parse(source: string, file: string): { frontmatter: ReturnType<typeof validateGuideFrontmatter>; body: string } { const match = source.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/); if (!match || match[1] === undefined || match[2] === undefined) throw new Error(`${file}: forventer YAML-frontmatter`); if (/<\/?[a-z][^>]*>/i.test(match[2])) throw new Error(`${file}: rå HTML er ikke tilladt i guide-Markdown`); return { frontmatter: validateGuideFrontmatter(Bun.YAML.parse(match[1]), file), body: match[2] }; }
const guides: Guide[] = [];
for (const file of await markdownFiles(contentRoot)) { const source = await Bun.file(file).text(); const { frontmatter, body } = parse(source, file); const folder = relative(contentRoot, dirname(file)); const route = `/${folder === "." ? "" : `${folder}/`}`; guides.push({ ...frontmatter, route, markdownRoute: route === "/" ? "/index.md" : `/${folder}.md`, source, body }); }
if (new Set(guides.map((guide) => guide.id)).size !== guides.length || new Set(guides.map((guide) => guide.route)).size !== guides.length) throw new Error("Guide-id eller route er ikke unik");
const manifest = `// Generated by scripts/generate-guides.ts. Do not edit by hand.\nimport type { PublicPage } from "../pages.ts";\nexport const GENERATED_GUIDES: readonly PublicPage[] = ${JSON.stringify(guides.map(({ body, source, ...guide }) => ({ ...guide, source: `web/public${guide.route}index.html`, markdownSource: `web/public${guide.markdownRoute}`, title: guide.title, description: guide.description, openGraphTitle: guide.title, openGraphDescription: guide.summary, sitemap: true, navigationGroup: guide.route.startsWith("/forloeb/") ? "journey" : guide.route.startsWith("/platforme/") ? "platform" : "support", readOnlyBoundary: true })), null, 2)} as const;\n`;
for (const guide of guides) { await Bun.write(join(publicRoot, guide.markdownRoute), guide.source); await Bun.write(join(publicRoot, guide.route, "index.html"), renderGuideHtml(guide, guide.body, guide.route, guide.markdownRoute)); }
await Bun.write(join(root, "web/generated/guides.ts"), manifest);
console.log(`Genererede ${guides.length} guide(r)`);
